-- ===============================
-- STORES & STORE OWNERS
-- ===============================

CREATE TABLE store_owner (
  store_owner_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(255) NOT NULL,
  email           VARCHAR(255) UNIQUE NOT NULL,
  password_hash   TEXT NOT NULL,
  phone           VARCHAR(50),
  address         JSONB,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE store (
  store_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_owner_id  BIGINT UNIQUE NOT NULL REFERENCES store_owner(store_owner_id),
  name            VARCHAR(255) NOT NULL,
  domain          VARCHAR(255) UNIQUE,
  currency        VARCHAR(10) DEFAULT 'USD',
  timezone        VARCHAR(100) DEFAULT 'UTC',
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ===============================
-- CATEGORIES
-- ===============================

CREATE TABLE category_definition (
  category_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(255) NOT NULL UNIQUE,
  parent_id       BIGINT REFERENCES category_definition(category_id)
);

CREATE TABLE store_category (
  store_id        BIGINT NOT NULL REFERENCES store(store_id) ON DELETE CASCADE,
  category_id     BIGINT NOT NULL REFERENCES category_definition(category_id) ON DELETE CASCADE,
  PRIMARY KEY (store_id, category_id)
);

-- ===============================
-- PRODUCTS & VARIANTS
-- ===============================

CREATE TABLE product (
  product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id        BIGINT NOT NULL REFERENCES store(store_id),
  category_id     BIGINT NOT NULL REFERENCES category_definition(category_id),
  name            VARCHAR(255) NOT NULL,
  slug            VARCHAR(255),
  description     TEXT,
  brand           VARCHAR(255),
  stock_quantity  INT DEFAULT 0 NOT NULL,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  in_stock        BOOLEAN DEFAULT TRUE NOT NULL,
  deleted_at      TIMESTAMP WITH TIME ZONE NULL,
  default_variant_id BIGINT,
  CONSTRAINT unique_slug_per_store UNIQUE (store_id, slug)
);

CREATE TABLE product_variant (
  variant_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT NOT NULL REFERENCES product(product_id),
  store_id        BIGINT NOT NULL REFERENCES store(store_id),
  attribute_hash TEXT NOT NULL,
  sku             VARCHAR(100) NOT NULL,
  price           DECIMAL(10,2) NOT NULL,
  stock_quantity  INT DEFAULT 0 NOT NULL,
  primary_image_url  VARCHAR(500) NOT NULL,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  deleted_at      TIMESTAMP WITH TIME ZONE NULL,
  UNIQUE (store_id, sku)
);

CREATE TABLE attribute_definition (
  attribute_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE variant_attribute_value (
  variant_id      BIGINT NOT NULL REFERENCES product_variant(variant_id) ON DELETE CASCADE,
  attribute_id    BIGINT NOT NULL REFERENCES attribute_definition(attribute_id),
  value           TEXT NOT NULL,
  PRIMARY KEY (variant_id, attribute_id)
);

CREATE TABLE category_attribute (
  category_id     BIGINT NOT NULL REFERENCES category_definition(category_id) ON DELETE CASCADE,
  attribute_id    BIGINT NOT NULL REFERENCES attribute_definition(attribute_id),
  PRIMARY KEY (category_id, attribute_id)
);

CREATE TABLE product_variant_image (
  image_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_variant_id      BIGINT NOT NULL REFERENCES product_variant(variant_id) ON DELETE CASCADE,
  image_url       VARCHAR(500) NOT NULL,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE product
ADD CONSTRAINT fk_product_default_variant
FOREIGN KEY (default_variant_id)
REFERENCES product_variant(variant_id);

-- ===============================
-- CUSTOMERS
-- ===============================

CREATE TABLE customer (
  customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id        BIGINT NOT NULL REFERENCES store(store_id),
  name            VARCHAR(255) NOT NULL,
  email           VARCHAR(255) NOT NULL,
  password_hash   TEXT NOT NULL,
  phone           VARCHAR(50),
  address         JSONB,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE (store_id, email)
);

CREATE TABLE visitor_session (
  session_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id       BIGINT NOT NULL REFERENCES store(store_id),
  customer_id    BIGINT REFERENCES customer(customer_id), -- nullable for guests
  ip_address     INET,
  user_agent     TEXT,
  first_seen_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_seen_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  is_returning   BOOLEAN DEFAULT FALSE
);

-- ===============================
-- SHOPPING CART & ORDERS
-- ===============================

CREATE TABLE cart (
  cart_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id     BIGINT REFERENCES customer(customer_id),
  store_id        BIGINT NOT NULL REFERENCES store(store_id),
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE cart_item (
  cart_item_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id         BIGINT NOT NULL REFERENCES cart(cart_id),
  variant_id      BIGINT NOT NULL REFERENCES product_variant(variant_id),
  quantity        INT NOT NULL CHECK (quantity > 0),
  unit_price      DECIMAL(10,2) NOT NULL,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE customer_order (
  order_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id        BIGINT NOT NULL REFERENCES store(store_id),
  customer_id     BIGINT REFERENCES customer(customer_id),
  session_id      UUID NOT NULL REFERENCES visitor_session(session_id),
  total_amount    DECIMAL(10,2),
  status          VARCHAR(50) DEFAULT 'pending',
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE order_item (
  order_item_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        BIGINT NOT NULL REFERENCES customer_order(order_id),
  variant_id      BIGINT REFERENCES product_variant(variant_id),
  quantity        INT NOT NULL CHECK (quantity > 0),
  unit_price      DECIMAL(10,2),
  subtotal        DECIMAL(10,2)
);

CREATE TABLE payment (
  payment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        BIGINT NOT NULL REFERENCES customer_order(order_id),
  method          VARCHAR(50),
  amount          DECIMAL(10,2),
  status          VARCHAR(50) DEFAULT 'pending',
  transaction_ref VARCHAR(255),
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE shipment (
  shipment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        BIGINT NOT NULL REFERENCES customer_order(order_id),
  tracking_number VARCHAR(255),
  carrier         VARCHAR(255),
  shipped_at      TIMESTAMP WITH TIME ZONE,
  delivered_at    TIMESTAMP WITH TIME ZONE CHECK (delivered_at >= shipped_at),
  status          VARCHAR(50) DEFAULT 'pending'
);

CREATE TABLE product_view (
  product_view_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id      BIGINT NOT NULL REFERENCES product(product_id),
  store_id        BIGINT NOT NULL REFERENCES store(store_id),
  session_id      UUID NOT NULL REFERENCES visitor_session(session_id),
  viewed_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE cart_event (
  cart_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id    UUID NOT NULL REFERENCES visitor_session(session_id),
  product_id    BIGINT NOT NULL REFERENCES product(product_id),
  variant_id    BIGINT REFERENCES product_variant(variant_id),
  event_type    VARCHAR(20) CHECK (event_type IN ('add', 'remove')),
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE admin (
  admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email    VARCHAR(255) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);