// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"time"

	"github.com/Secure-Website-Builder/Backend/internal/types"
	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Admin struct {
	AdminID      int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

type AttributeDefinition struct {
	AttributeID int64
	Name        string
}

type Cart struct {
	CartID     int64
	StoreID    int64
	SessionID  uuid.UUID
	CustomerID sql.NullInt64
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
}

type CartEvent struct {
	CartEventID int64
	SessionID   uuid.UUID
	ProductID   int64
	VariantID   sql.NullInt64
	EventType   sql.NullString
	CreatedAt   time.Time
}

type CartItem struct {
	CartItemID int64
	CartID     int64
	VariantID  int64
	Quantity   int32
	UnitPrice  string
	CreatedAt  time.Time
}

type CategoryAttribute struct {
	CategoryID  int64
	AttributeID int64
	IsRequired  bool
}

type CategoryDefinition struct {
	CategoryID int64
	Name       string
	ParentID   sql.NullInt64
}

type Customer struct {
	CustomerID   int64
	StoreID      int64
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Address      types.NullableAddress
	CreatedAt    time.Time
}

type CustomerOrder struct {
	OrderID     int64
	StoreID     int64
	CustomerID  sql.NullInt64
	SessionID   uuid.UUID
	TotalAmount string
	Status      sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}

type OrderItem struct {
	OrderItemID int64
	OrderID     int64
	VariantID   int64
	Quantity    int32
	UnitPrice   string
	Subtotal    string
}

type Payment struct {
	PaymentID      int64
	OrderID        int64
	Method         string
	Amount         string
	Status         string
	TransactionRef sql.NullString
	CreatedAt      time.Time
}

type Product struct {
	ProductID        int64
	StoreID          int64
	CategoryID       int64
	Name             string
	Slug             sql.NullString
	Description      sql.NullString
	Brand            sql.NullString
	StockQuantity    int32
	CreatedAt        time.Time
	UpdatedAt        sql.NullTime
	InStock          bool
	DeletedAt        sql.NullTime
	DefaultVariantID sql.NullInt64
}

type ProductVariant struct {
	VariantID       int64
	ProductID       int64
	StoreID         int64
	AttributeHash   string
	Sku             string
	Price           string
	StockQuantity   int32
	PrimaryImageUrl sql.NullString
	CreatedAt       time.Time
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type ProductVariantImage struct {
	ImageID          int64
	ProductVariantID int64
	ImageUrl         string
	CreatedAt        time.Time
}

type ProductView struct {
	ProductViewID int64
	ProductID     int64
	StoreID       int64
	SessionID     uuid.UUID
	ViewedAt      sql.NullTime
}

type RefreshToken struct {
	RefreshTokenID int64
	Token          string
	UserID         int64
	UserRole       string
	StoreID        sql.NullInt64
	ExpiresAt      time.Time
	Revoked        sql.NullBool
	CreatedAt      time.Time
}

type Shipment struct {
	ShipmentID     int64
	OrderID        int64
	TrackingNumber sql.NullString
	Carrier        sql.NullString
	ShippedAt      sql.NullTime
	DeliveredAt    sql.NullTime
	Status         sql.NullString
}

type Store struct {
	StoreID        int64
	StoreOwnerID   int64
	Name           string
	Domain         sql.NullString
	DownloadStatus string
	Currency       sql.NullString
	Timezone       sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type StoreCategory struct {
	StoreID    int64
	CategoryID int64
}

type StoreOwner struct {
	StoreOwnerID int64
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Address      types.NullableAddress
	CreatedAt    time.Time
}

type VariantAttributeValue struct {
	VariantID   int64
	AttributeID int64
	Value       string
}

type VisitorSession struct {
	SessionID   uuid.UUID
	StoreID     int64
	CustomerID  sql.NullInt64
	IpAddress   pqtype.Inet
	UserAgent   sql.NullString
	FirstSeenAt sql.NullTime
	LastSeenAt  sql.NullTime
	IsReturning sql.NullBool
}
