// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AttributeDefinition struct {
	AttributeID int64
	StoreID     int64
	Name        string
	DataType    string
	CategoryID  sql.NullInt64
}

type Cart struct {
	CartID     int64
	CustomerID sql.NullInt64
	StoreID    int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type CartEvent struct {
	CartEventID int64
	SessionID   uuid.UUID
	ProductID   int64
	VariantID   sql.NullInt64
	EventType   sql.NullString
	CreatedAt   sql.NullTime
}

type CartItem struct {
	CartItemID int64
	CartID     int64
	VariantID  int64
	Quantity   int32
	UnitPrice  sql.NullString
	CreatedAt  sql.NullTime
}

type Customer struct {
	CustomerID int64
	StoreID    int64
	Name       sql.NullString
	Email      sql.NullString
	Phone      sql.NullString
	Address    pqtype.NullRawMessage
	CreatedAt  sql.NullTime
}

type CustomerOrder struct {
	OrderID     int64
	StoreID     int64
	CustomerID  sql.NullInt64
	SessionID   uuid.UUID
	TotalAmount sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type OptionType struct {
	OptionTypeID int64
	StoreID      int64
	Name         string
}

type OptionValue struct {
	OptionValueID int64
	OptionTypeID  int64
	Value         string
}

type OrderItem struct {
	OrderItemID int64
	OrderID     int64
	VariantID   sql.NullInt64
	Quantity    int32
	UnitPrice   sql.NullString
	Subtotal    sql.NullString
}

type Payment struct {
	PaymentID      int64
	OrderID        int64
	Method         sql.NullString
	Amount         sql.NullString
	Status         sql.NullString
	TransactionRef sql.NullString
	CreatedAt      sql.NullTime
}

type Product struct {
	ProductID        int64
	StoreID          int64
	CategoryID       sql.NullInt64
	Name             string
	Slug             sql.NullString
	Description      sql.NullString
	Brand            sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	InStock          bool
	DeletedAt        sql.NullTime
	DefaultVariantID sql.NullInt64
}

type ProductAttributeValue struct {
	ProductID    int64
	AttributeID  int64
	ValueText    sql.NullString
	ValueNumber  sql.NullString
	ValueBoolean sql.NullBool
}

type ProductCategory struct {
	CategoryID int64
	StoreID    int64
	Name       string
	ParentID   sql.NullInt64
	CreatedAt  sql.NullTime
}

type ProductImage struct {
	ImageID   int64
	ProductID int64
	ImageUrl  string
	IsPrimary bool
}

type ProductVariant struct {
	VariantID     int64
	ProductID     int64
	Sku           string
	Price         string
	StockQuantity int32
	ImageUrl      string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type ProductView struct {
	ProductViewID int64
	ProductID     int64
	StoreID       int64
	SessionID     uuid.UUID
	ViewedAt      sql.NullTime
}

type Shipment struct {
	ShipmentID     int64
	OrderID        int64
	TrackingNumber sql.NullString
	Carrier        sql.NullString
	ShippedAt      sql.NullTime
	DeliveredAt    sql.NullTime
	Status         sql.NullString
}

type Store struct {
	StoreID      int64
	StoreOwnerID int64
	Name         string
	Domain       sql.NullString
	Currency     sql.NullString
	Timezone     sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type StoreOwner struct {
	StoreOwnerID int64
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
}

type VariantOption struct {
	VariantID     int64
	OptionValueID int64
}

type VisitorSession struct {
	SessionID   uuid.UUID
	StoreID     int64
	CustomerID  sql.NullInt64
	IpAddress   pqtype.Inet
	UserAgent   sql.NullString
	FirstSeenAt sql.NullTime
	LastSeenAt  sql.NullTime
	IsReturning sql.NullBool
}
